-- Fix Broadcast_text errors, not sure they are used in TBC
REPLACE INTO `broadcast_text` (`ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild`) VALUES 
('23254', '0', 'Dark times make for strange friendships. It may be worth visiting old Lordaeron to watch the Forsaken burn their little man of wicker.', 'Dark times make for strange friendships. It may be worth visiting old Lordaeron to watch the Forsaken burn their little man of wicker.', '0', '0', '0', '0', '0', '0', '0', '0', '1', '18019'),
('23255', '0', 'I understand this holiday is a creation not of our allies, but the Horde. Why we follow suit, I do not know.', 'I understand this holiday is a creation not of our allies, but the Horde. Why we follow suit, I do not know.', '0', '0', '0', '0', '0', '0', '0', '0', '1', '18019'),
('23256', '0', 'We\'re celebrating the who breaking free of the what? Bah, who cares?! More candy!', 'We\'re celebrating the who breaking free of the what? Bah, who cares?! More candy!', '0', '0', '0', '0', '0', '0', '0', '0', '1', '18019'),
('23260', '0', 'To celebrate the birth of yet another deadly enemy is an odd thing, to say the least. Still, we will join our allies in their festivities.', 'To celebrate the birth of yet another deadly enemy is an odd thing, to say the least. Still, we will join our allies in their festivities.', '1', '0', '0', '0', '0', '0', '0', '0', '1', '18019'),
('23261', '0', 'The Forsaken are right to celebrate their freedom. What else is more important?', 'The Forsaken are right to celebrate their freedom. What else is more important?', '0', '0', '0', '0', '0', '0', '0', '0', '1', '18019'),
('23264', '0', 'During Hallow\'s End we celebrate the day that the Banshee Queen herself delivered us from the clutches of the Lich King and the Scourge. Be sure to attend the Wickerman Festival that is held each evening outside Undercity.', 'During Hallow\'s End we celebrate the day that the Banshee Queen herself delivered us from the clutches of the Lich King and the Scourge. Be sure to attend the Wickerman Festival that is held each evening outside Undercity.', '0', '0', '0', '0', '0', '0', '0', '0', '1', '18019'),
('23633', '0', 'No other holiday matches the feasting and drinking of Brewfest!', 'No other holiday matches the feasting and drinking of Brewfest!', '396', '92', '0', '0', '4', '0', '0', '0', '1', '18019');


-- Gameobject errors
-- Ship (The Bravery) compared it with cmangos and oregoncore Database
UPDATE `gameobject_template` SET `Data0`='295' WHERE (`entry`='176310');

-- The Shattered Halls compared it with cmangos and oregoncore Database
UPDATE `gameobject_template` SET `Data1`='1687', `Data2`='327680' WHERE (`entry`='184912');

-- Objects added with wotlk 
DELETE FROM gameobject_template WHERE entry = "186799";
DELETE FROM gameobject_template WHERE entry = "190557"; 
DELETE FROM gameobject_template WHERE entry = "187879";
DELETE FROM gameobject_template WHERE entry = "187885";
DELETE FROM gameobject_template WHERE entry = "187886";
DELETE FROM gameobject_template WHERE entry = "188112";
DELETE FROM gameobject_template WHERE entry = "188423";
DELETE FROM gameobject_template WHERE entry = "188445";
DELETE FROM gameobject_template WHERE entry = "188474";
DELETE FROM gameobject_template WHERE entry = "188491";
DELETE FROM gameobject_template WHERE entry = "191303";
DELETE FROM gameobject_template WHERE entry = "186371";
DELETE FROM gameobject_template WHERE entry = "186586";
DELETE FROM gameobject_template WHERE entry = "186656";
DELETE FROM gameobject_template WHERE entry = "186657";
DELETE FROM gameobject_template WHERE entry = "186770";
DELETE FROM gameobject_template WHERE entry = "186863";
DELETE FROM gameobject_template WHERE entry = "186894";
DELETE FROM gameobject_template WHERE entry = "186949";
DELETE FROM gameobject_template WHERE entry = "188264";
DELETE FROM gameobject_template WHERE entry = "188288";
DELETE FROM gameobject_template WHERE entry = "188289";
DELETE FROM gameobject_template WHERE entry = "189290";
DELETE FROM gameobject_template WHERE entry = "189972";
DELETE FROM gameobject_template WHERE entry = "190688";
DELETE FROM gameobject_template WHERE entry = "191133";
DELETE FROM gameobject_template WHERE entry = "191136";
DELETE FROM gameobject_template WHERE entry = "191574";
DELETE FROM gameobject_template WHERE entry = "193402";
DELETE FROM gameobject_template WHERE entry = "188133";
DELETE FROM gameobject_template WHERE entry = "191543";
DELETE FROM gameobject_template WHERE entry = "192523";
DELETE FROM gameobject_template WHERE entry = "193622";
DELETE FROM gameobject_template WHERE entry = "186718";
DELETE FROM gameobject_template WHERE entry = "187690";
DELETE FROM gameobject_template WHERE entry = "188104";
DELETE FROM gameobject_template WHERE entry = "188711";
DELETE FROM gameobject_template where entry = "188104";
DELETE FROM gameobject_template where entry = "188711";
DELETE FROM gameobject_template where entry = "189985";
DELETE FROM gameobject_template where entry = "190191";
DELETE FROM gameobject_template where entry = "190498";
DELETE FROM gameobject_template where entry = "190550";
DELETE FROM gameobject_template where entry = "190731";
DELETE FROM gameobject_template where entry = "190949";
DELETE FROM gameobject_template where entry = "192152";
DELETE FROM gameobject_template where entry = "192783";
DELETE FROM gameobject_template where entry = "193052";
DELETE FROM gameobject_template where entry = "193053";
DELETE FROM gameobject_template where entry = "193061";
DELETE FROM gameobject_template where entry = "193171";
DELETE FROM gameobject_template where entry = "193207";
DELETE FROM gameobject_template where entry = "193948";
DELETE FROM gameobject_template where entry = "193955";
DELETE FROM gameobject_template where entry = "193206";
DELETE FROM gameobject_template where entry = "193425";
DELETE FROM gameobject_template where entry = "193169";
DELETE FROM gameobject_template where entry = "192075";
DELETE FROM gameobject_template where entry = "193952";
DELETE FROM gameobject_template where entry = "193170";
DELETE FROM gameobject_template where entry = "192675";
DELETE FROM gameobject_template where entry = "194539";
DELETE FROM gameobject_template where entry = "194537";
DELETE FROM gameobject_template where entry = "194538";
DELETE FROM gameobject_template where entry = "194618";
DELETE FROM gameobject_template where entry = "194622";
DELETE FROM gameobject_template where entry = "194909";
DELETE FROM gameobject_template where entry = "194908";
DELETE FROM gameobject_template where entry = "194264";
DELETE FROM gameobject_template where entry = "192786";
DELETE FROM gameobject_template where entry = "194151";
DELETE FROM gameobject_template where entry = "195308";
DELETE FROM gameobject_template where entry = "196398";
DELETE FROM gameobject_template where entry = "195309";
DELETE FROM gameobject_template where entry = "195087";
DELETE FROM gameobject_template where entry = "190549";
DELETE FROM gameobject_template where entry = "191578";
DELETE FROM gameobject_template where entry = "186464";
DELETE FROM gameobject_template where entry = "186487";
DELETE FROM gameobject_template where entry = "186599";
DELETE FROM gameobject_template where entry = "186613";
DELETE FROM gameobject_template where entry = "186952";
DELETE FROM gameobject_template where entry = "186959";
DELETE FROM gameobject_template where entry = "187382";
DELETE FROM gameobject_template where entry = "187458";
DELETE FROM gameobject_template where entry = "187666";
DELETE FROM gameobject_template where entry = "187681";
DELETE FROM gameobject_template where entry = "187705";
DELETE FROM gameobject_template where entry = "187706";
DELETE FROM gameobject_template where entry = "187763";
DELETE FROM gameobject_template where entry = "187849";
DELETE FROM gameobject_template where entry = "187893";
DELETE FROM gameobject_template where entry = "187894";
DELETE FROM gameobject_template where entry = "187904";
DELETE FROM gameobject_template where entry = "188019";
DELETE FROM gameobject_template where entry = "188086";
DELETE FROM gameobject_template where entry = "188105";
DELETE FROM gameobject_template where entry = "188155";
DELETE FROM gameobject_template where entry = "188161";
DELETE FROM gameobject_template where entry = "188175";
DELETE FROM gameobject_template where entry = "188358";
DELETE FROM gameobject_template where entry = "188369";
DELETE FROM gameobject_template where entry = "188420";
DELETE FROM gameobject_template where entry = "188510";
DELETE FROM gameobject_template where entry = "188564";
DELETE FROM gameobject_template where entry = "188660";
DELETE FROM gameobject_template where entry = "188664";
DELETE FROM gameobject_template where entry = "188672";
DELETE FROM gameobject_template where entry = "188679";
DELETE FROM gameobject_template where entry = "188690";
DELETE FROM gameobject_template where entry = "188694";
DELETE FROM gameobject_template where entry = "188698";
DELETE FROM gameobject_template where entry = "188707";
DELETE FROM gameobject_template where entry = "188708";
DELETE FROM gameobject_template where entry = "189331";
DELETE FROM gameobject_template where entry = "189984";
DELETE FROM gameobject_template where entry = "190033";
DELETE FROM gameobject_template where entry = "190202";
DELETE FROM gameobject_template where entry = "190224";
DELETE FROM gameobject_template where entry = "190364";
DELETE FROM gameobject_template where entry = "190499";
DELETE FROM gameobject_template where entry = "190501";
DELETE FROM gameobject_template where entry = "190545";
DELETE FROM gameobject_template where entry = "190708";
DELETE FROM gameobject_template where entry = "190739";
DELETE FROM gameobject_template where entry = "190781";
DELETE FROM gameobject_template where entry = "190782";
DELETE FROM gameobject_template where entry = "190916";
DELETE FROM gameobject_template where entry = "191122";
DELETE FROM gameobject_template where entry = "191124";
DELETE FROM gameobject_template where entry = "191141";
DELETE FROM gameobject_template where entry = "191192";
DELETE FROM gameobject_template where entry = "191233";
DELETE FROM gameobject_template where entry = "191522";
DELETE FROM gameobject_template where entry = "191823";
DELETE FROM gameobject_template where entry = "192011";
DELETE FROM gameobject_template where entry = "192165";
DELETE FROM gameobject_template where entry = "192462";
DELETE FROM gameobject_template where entry = "192535";
DELETE FROM gameobject_template where entry = "192540";
DELETE FROM gameobject_template where entry = "192560";
DELETE FROM gameobject_template where entry = "193004";
DELETE FROM gameobject_template where entry = "193090";
DELETE FROM gameobject_template where entry = "193387";
DELETE FROM gameobject_template where entry = "193580";
DELETE FROM gameobject_template where entry = "193947";
DELETE FROM gameobject_template where entry = "193993";
DELETE FROM gameobject_template where entry = "194241";
DELETE FROM gameobject_template where entry = "194291";
DELETE FROM gameobject_template where entry = "194425";
DELETE FROM gameobject_template where entry = "195328";
DELETE FROM gameobject_template where entry = "195329";
DELETE FROM gameobject_template where entry = "195330";
DELETE FROM gameobject_template where entry = "201590";
DELETE FROM gameobject_template where entry = "201796";
DELETE FROM gameobject_template where entry = "186316";
DELETE FROM gameobject_template where entry = "188597";
DELETE FROM gameobject_template where entry = "188598";
DELETE FROM gameobject_template where entry = "190203";
DELETE FROM gameobject_template where entry = "190204";
DELETE FROM gameobject_template where entry = "190205";
DELETE FROM gameobject_template where entry = "190206";
DELETE FROM gameobject_template where entry = "190207";