--
UPDATE `creature_template` SET `name` = 'Timber Wolf', `PetSpellDataId` = 0 WHERE `entry` = 69;
UPDATE `creature_template` SET `name` = 'Young Fleshripper', `PetSpellDataId` = 0 WHERE `entry` = 199;
UPDATE `creature_template` SET `name` = 'Starving Dire Wolf', `PetSpellDataId` = 0 WHERE `entry` = 213;
UPDATE `creature_template` SET `name` = 'Young Wolf', `PetSpellDataId` = 0 WHERE `entry` = 299;
UPDATE `creature_template` SET `name` = 'Dire Condor', `PetSpellDataId` = 0 WHERE `entry` = 428;
UPDATE `creature_template` SET `name` = 'Vultros', `PetSpellDataId` = 0 WHERE `entry` = 462;
UPDATE `creature_template` SET `name` = 'Mangy Wolf', `PetSpellDataId` = 0 WHERE `entry` = 525;
UPDATE `creature_template` SET `name` = 'Rabid Dire Wolf', `PetSpellDataId` = 0 WHERE `entry` = 565;
UPDATE `creature_template` SET `name` = 'Stranglethorn Raptor', `PetSpellDataId` = 0 WHERE `entry` = 685;
UPDATE `creature_template` SET `name` = 'Lashtail Raptor', `PetSpellDataId` = 0 WHERE `entry` = 686;
UPDATE `creature_template` SET `name` = 'Jungle Stalker', `PetSpellDataId` = 0 WHERE `entry` = 687;
UPDATE `creature_template` SET `name` = 'Bloodscalp Tiger', `PetSpellDataId` = 0 WHERE `entry` = 698;
UPDATE `creature_template` SET `name` = 'Ragged Timber Wolf', `PetSpellDataId` = 0 WHERE `entry` = 704;
UPDATE `creature_template` SET `name` = 'Ragged Young Wolf', `PetSpellDataId` = 0 WHERE `entry` = 705;
UPDATE `creature_template` SET `name` = 'Tethis', `PetSpellDataId` = 0 WHERE `entry` = 730;
UPDATE `creature_template` SET `name` = 'Stranglethorn Tigress', `PetSpellDataId` = 0 WHERE `entry` = 772;
UPDATE `creature_template` SET `name` = 'Sand Crawler', `PetSpellDataId` = 0 WHERE `entry` = 830;
UPDATE `creature_template` SET `name` = 'Sea Crawler', `PetSpellDataId` = 0 WHERE `entry` = 831;
UPDATE `creature_template` SET `name` = 'Young Jungle Stalker', `PetSpellDataId` = 0 WHERE `entry` = 854;
UPDATE `creature_template` SET `name` = 'Young Stranglethorn Raptor', `PetSpellDataId` = 0 WHERE `entry` = 855;
UPDATE `creature_template` SET `name` = 'Young Lashtail Raptor', `PetSpellDataId` = 0 WHERE `entry` = 856;
UPDATE `creature_template` SET `name` = 'Sorrow Spinner', `PetSpellDataId` = 0 WHERE `entry` = 858;
UPDATE `creature_template` SET `name` = 'Young Black Ravager', `PetSpellDataId` = 0 WHERE `entry` = 923;
UPDATE `creature_template` SET `name` = 'Kurzen War Panther', `PetSpellDataId` = 0 WHERE `entry` = 977;
UPDATE `creature_template` SET `name` = 'Highland Raptor', `PetSpellDataId` = 0 WHERE `entry` = 1015;
UPDATE `creature_template` SET `name` = 'Highland Lashtail', `PetSpellDataId` = 0 WHERE `entry` = 1016;
UPDATE `creature_template` SET `name` = 'Highland Scytheclaw', `PetSpellDataId` = 0 WHERE `entry` = 1017;
UPDATE `creature_template` SET `name` = 'Highland Razormaw', `PetSpellDataId` = 0 WHERE `entry` = 1018;
UPDATE `creature_template` SET `name` = 'Elder Razormaw', `PetSpellDataId` = 0 WHERE `entry` = 1019;
UPDATE `creature_template` SET `name` = 'Mottled Raptor', `PetSpellDataId` = 0 WHERE `entry` = 1020;
UPDATE `creature_template` SET `name` = 'Mottled Screecher', `PetSpellDataId` = 0 WHERE `entry` = 1021;
UPDATE `creature_template` SET `name` = 'Mottled Scytheclaw', `PetSpellDataId` = 0 WHERE `entry` = 1022;
UPDATE `creature_template` SET `name` = 'Mottled Razormaw', `PetSpellDataId` = 0 WHERE `entry` = 1023;
UPDATE `creature_template` SET `name` = 'Sawtooth Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 1082;
UPDATE `creature_template` SET `name` = 'Young Sawtooth Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 1084;
UPDATE `creature_template` SET `name` = 'Elder Stranglethorn Tiger', `PetSpellDataId` = 0 WHERE `entry` = 1085;
UPDATE `creature_template` SET `name` = 'Fleshripper', `PetSpellDataId` = 0 WHERE `entry` = 1109;
UPDATE `creature_template` SET `name` = 'Young Black Bear', `PetSpellDataId` = 0 WHERE `entry` = 1128;
UPDATE `creature_template` SET `name` = 'Razormaw Matriarch', `PetSpellDataId` = 0 WHERE `entry` = 1140;
UPDATE `creature_template` SET `name` = 'River Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 1150;
UPDATE `creature_template` SET `name` = 'Saltwater Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 1151;
UPDATE `creature_template` SET `name` = 'Snapjaw Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 1152;
UPDATE `creature_template` SET `name` = 'Cliff Lurker', `PetSpellDataId` = 0 WHERE `entry` = 1184;
UPDATE `creature_template` SET `name` = 'Elder Black Bear', `PetSpellDataId` = 0 WHERE `entry` = 1186;
UPDATE `creature_template` SET `name` = 'Grizzled Black Bear', `PetSpellDataId` = 0 WHERE `entry` = 1188;
UPDATE `creature_template` SET `name` = 'Mountain Buzzard', `PetSpellDataId` = 0 WHERE `entry` = 1194;
UPDATE `creature_template` SET `name` = 'Snow Leopard', `PetSpellDataId` = 0 WHERE `entry` = 1201;
UPDATE `creature_template` SET `name` = 'Sarltooth', `PetSpellDataId` = 0 WHERE `entry` = 1353;
UPDATE `creature_template` SET `name` = 'Wetlands Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 1400;
UPDATE `creature_template` SET `name` = 'Young Wetlands Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 1417;
UPDATE `creature_template` SET `name` = 'Young Scavenger', `PetSpellDataId` = 0 WHERE `entry` = 1508;
UPDATE `creature_template` SET `name` = 'Enraged Silverback Gorilla', `PetSpellDataId` = 0 WHERE `entry` = 1511;
UPDATE `creature_template` SET `name` = 'Duskbat', `PetSpellDataId` = 0 WHERE `entry` = 1512;
UPDATE `creature_template` SET `name` = 'Mangy Duskbat', `PetSpellDataId` = 0 WHERE `entry` = 1513;
UPDATE `creature_template` SET `name` = 'Konda', `PetSpellDataId` = 0 WHERE `entry` = 1516;
UPDATE `creature_template` SET `name` = 'Vampiric Duskbat', `PetSpellDataId` = 0 WHERE `entry` = 1554;
UPDATE `creature_template` SET `name` = 'Silverback Patriarch', `PetSpellDataId` = 0 WHERE `entry` = 1558;
UPDATE `creature_template` SET `name` = 'King Mukla', `PetSpellDataId` = 0 WHERE `entry` = 1559;
UPDATE `creature_template` SET `name` = 'Mottled Worg', `PetSpellDataId` = 0 WHERE `entry` = 1766;
UPDATE `creature_template` SET `name` = 'Moss Stalker', `PetSpellDataId` = 0 WHERE `entry` = 1780;
UPDATE `creature_template` SET `name` = 'Mist Creeper', `PetSpellDataId` = 0 WHERE `entry` = 1781;
UPDATE `creature_template` SET `name` = 'Giant Grizzled Bear', `PetSpellDataId` = 0 WHERE `entry` = 1797;
UPDATE `creature_template` SET `name` = 'Diseased Black Bear', `PetSpellDataId` = 0 WHERE `entry` = 1815;
UPDATE `creature_template` SET `name` = 'Carrion Lurker', `PetSpellDataId` = 0 WHERE `entry` = 1821;
UPDATE `creature_template` SET `name` = 'Webwood Spider', `PetSpellDataId` = 0 WHERE `entry` = 1986;
UPDATE `creature_template` SET `name` = 'Strigid Screecher', `PetSpellDataId` = 0 WHERE `entry` = 1996;
UPDATE `creature_template` SET `name` = 'Webwood Lurker', `PetSpellDataId` = 0 WHERE `entry` = 1998;
UPDATE `creature_template` SET `name` = 'Young Nightsaber', `PetSpellDataId` = 0 WHERE `entry` = 2031;
UPDATE `creature_template` SET `name` = 'Mangy Nightsaber', `PetSpellDataId` = 0 WHERE `entry` = 2032;
UPDATE `creature_template` SET `name` = 'Elder Nightsaber', `PetSpellDataId` = 0 WHERE `entry` = 2033;
UPDATE `creature_template` SET `name` = 'Feral Nightsaber', `PetSpellDataId` = 0 WHERE `entry` = 2034;
UPDATE `creature_template` SET `name` = 'Nightsaber Stalker', `PetSpellDataId` = 0 WHERE `entry` = 2043;
UPDATE `creature_template` SET `name` = 'Moonstalker', `PetSpellDataId` = 0 WHERE `entry` = 2069;
UPDATE `creature_template` SET `name` = 'Moonstalker Matriarch', `PetSpellDataId` = 0 WHERE `entry` = 2071;
UPDATE `creature_template` SET `name` = 'Grizzled Thistle Bear', `PetSpellDataId` = 0 WHERE `entry` = 2165;
UPDATE `creature_template` SET `name` = 'Strider Clutchmother', `PetSpellDataId` = 0 WHERE `entry` = 2172;
UPDATE `creature_template` SET `name` = 'Shadowclaw', `PetSpellDataId` = 0 WHERE `entry` = 2175;
UPDATE `creature_template` SET `name` = 'Pygmy Tide Crawler', `PetSpellDataId` = 0 WHERE `entry` = 2231;
UPDATE `creature_template` SET `name` = 'Encrusted Tide Crawler', `PetSpellDataId` = 0 WHERE `entry` = 2233;
UPDATE `creature_template` SET `name` = 'Young Reef Crawler', `PetSpellDataId` = 0 WHERE `entry` = 2234;
UPDATE `creature_template` SET `name` = 'Reef Crawler', `PetSpellDataId` = 0 WHERE `entry` = 2235;
UPDATE `creature_template` SET `name` = 'Raging Reef Crawler', `PetSpellDataId` = 0 WHERE `entry` = 2236;
UPDATE `creature_template` SET `name` = 'Enraged Stanley', `PetSpellDataId` = 0 WHERE `entry` = 2275;
UPDATE `creature_template` SET `name` = 'Foreststrider', `PetSpellDataId` = 0 WHERE `entry` = 2322;
UPDATE `creature_template` SET `name` = 'Vicious Gray Bear', `PetSpellDataId` = 0 WHERE `entry` = 2354;
UPDATE `creature_template` SET `name` = 'Elder Gray Bear', `PetSpellDataId` = 0 WHERE `entry` = 2356;
UPDATE `creature_template` SET `name` = 'Hulking Mountain Lion', `PetSpellDataId` = 0 WHERE `entry` = 2407;
UPDATE `creature_template` SET `name` = 'Skymane Gorilla', `PetSpellDataId` = 0 WHERE `entry` = 2521;
UPDATE `creature_template` SET `name` = 'Southern Sand Crawler', `PetSpellDataId` = 0 WHERE `entry` = 2544;
UPDATE `creature_template` SET `name` = 'Highland Strider', `PetSpellDataId` = 0 WHERE `entry` = 2559;
UPDATE `creature_template` SET `name` = 'Highland Thrasher', `PetSpellDataId` = 0 WHERE `entry` = 2560;
UPDATE `creature_template` SET `name` = 'Highland Fleshstalker', `PetSpellDataId` = 0 WHERE `entry` = 2561;
UPDATE `creature_template` SET `name` = 'Elder Mesa Buzzard', `PetSpellDataId` = 0 WHERE `entry` = 2580;
UPDATE `creature_template` SET `name` = 'Elder Saltwater Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 2635;
UPDATE `creature_template` SET `name` = 'Vilebranch Wolf Pup', `PetSpellDataId` = 0 WHERE `entry` = 2680;
UPDATE `creature_template` SET `name` = 'Shadra', `PetSpellDataId` = 0 WHERE `entry` = 2707;
UPDATE `creature_template` SET `name` = 'Starving Buzzard', `PetSpellDataId` = 0 WHERE `entry` = 2829;
UPDATE `creature_template` SET `name` = 'Buzzard', `PetSpellDataId` = 0 WHERE `entry` = 2830;
UPDATE `creature_template` SET `name` = 'Giant Buzzard', `PetSpellDataId` = 0 WHERE `entry` = 2831;
UPDATE `creature_template` SET `name` = 'Mangy Silvermane', `PetSpellDataId` = 0 WHERE `entry` = 2923;
UPDATE `creature_template` SET `name` = 'Plainstrider', `PetSpellDataId` = 0 WHERE `entry` = 2955;
UPDATE `creature_template` SET `name` = 'Adult Plainstrider', `PetSpellDataId` = 0 WHERE `entry` = 2956;
UPDATE `creature_template` SET `name` = 'Mountain Cougar', `PetSpellDataId` = 0 WHERE `entry` = 2961;
UPDATE `creature_template` SET `name` = 'Wiry Swoop', `PetSpellDataId` = 0 WHERE `entry` = 2969;
UPDATE `creature_template` SET `name` = 'Swoop', `PetSpellDataId` = 0 WHERE `entry` = 2970;
UPDATE `creature_template` SET `name` = 'Taloned Swoop', `PetSpellDataId` = 0 WHERE `entry` = 2971;
UPDATE `creature_template` SET `name` = 'Surf Crawler', `PetSpellDataId` = 0 WHERE `entry` = 3107;
UPDATE `creature_template` SET `name` = 'Bloodtalon Taillasher', `PetSpellDataId` = 0 WHERE `entry` = 3122;
UPDATE `creature_template` SET `name` = 'Bloodtalon Scythemaw', `PetSpellDataId` = 0 WHERE `entry` = 3123;
UPDATE `creature_template` SET `name` = 'Clattering Scorpid', `PetSpellDataId` = 0 WHERE `entry` = 3125;
UPDATE `creature_template` SET `name` = 'Armored Scorpid', `PetSpellDataId` = 0 WHERE `entry` = 3126;
UPDATE `creature_template` SET `name` = 'Corrupted Bloodtalon Scythemaw', `PetSpellDataId` = 0 WHERE `entry` = 3227;
UPDATE `creature_template` SET `name` = 'Corrupted Surf Crawler', `PetSpellDataId` = 0 WHERE `entry` = 3228;
UPDATE `creature_template` SET `name` = 'Corrupted Dreadmaw Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 3231;
UPDATE `creature_template` SET `name` = 'Savannah Highmane', `PetSpellDataId` = 0 WHERE `entry` = 3243;
UPDATE `creature_template` SET `name` = 'Greater Plainstrider', `PetSpellDataId` = 0 WHERE `entry` = 3244;
UPDATE `creature_template` SET `name` = 'Sunscale Lashtail', `PetSpellDataId` = 0 WHERE `entry` = 3254;
UPDATE `creature_template` SET `name` = 'Sunscale Screecher', `PetSpellDataId` = 0 WHERE `entry` = 3255;
UPDATE `creature_template` SET `name` = 'Sunscale Scytheclaw', `PetSpellDataId` = 0 WHERE `entry` = 3256;
UPDATE `creature_template` SET `name` = 'Ishamuhale', `PetSpellDataId` = 0 WHERE `entry` = 3257;
UPDATE `creature_template` SET `name` = 'Savannah Huntress', `PetSpellDataId` = 0 WHERE `entry` = 3415;
UPDATE `creature_template` SET `name` = 'Savannah Matriarch', `PetSpellDataId` = 0 WHERE `entry` = 3416;
UPDATE `creature_template` SET `name` = 'Savannah Prowler', `PetSpellDataId` = 0 WHERE `entry` = 3425;
UPDATE `creature_template` SET `name` = 'Echeyakee', `PetSpellDataId` = 0 WHERE `entry` = 3475;
UPDATE `creature_template` SET `name` = 'Flatland Prowler', `PetSpellDataId` = 0 WHERE `entry` = 3566;
UPDATE `creature_template` SET `name` = 'Deviate Creeper', `PetSpellDataId` = 0 WHERE `entry` = 3632;
UPDATE `creature_template` SET `name` = 'Deviate Slayer', `PetSpellDataId` = 0 WHERE `entry` = 3633;
UPDATE `creature_template` SET `name` = 'Deviate Stalker', `PetSpellDataId` = 0 WHERE `entry` = 3634;
UPDATE `creature_template` SET `name` = 'Deviate Ravager', `PetSpellDataId` = 0 WHERE `entry` = 3636;
UPDATE `creature_template` SET `name` = 'Deviate Guardian', `PetSpellDataId` = 0 WHERE `entry` = 3637;
UPDATE `creature_template` SET `name` = 'Giant Ashenvale Bear', `PetSpellDataId` = 0 WHERE `entry` = 3811;
UPDATE `creature_template` SET `name` = 'Spined Crawler', `PetSpellDataId` = 0 WHERE `entry` = 3814;
UPDATE `creature_template` SET `name` = 'Wildthorn Stalker', `PetSpellDataId` = 0 WHERE `entry` = 3819;
UPDATE `creature_template` SET `name` = 'Wildthorn Venomspitter', `PetSpellDataId` = 0 WHERE `entry` = 3820;
UPDATE `creature_template` SET `name` = 'Ghostpaw Howler', `PetSpellDataId` = 0 WHERE `entry` = 3824;
UPDATE `creature_template` SET `name` = 'Bleak Worg', `PetSpellDataId` = 0 WHERE `entry` = 3861;
UPDATE `creature_template` SET `name` = 'Slavering Worg', `PetSpellDataId` = 0 WHERE `entry` = 3862;
UPDATE `creature_template` SET `name` = 'Vile Bat', `PetSpellDataId` = 0 WHERE `entry` = 3866;
UPDATE `creature_template` SET `name` = 'Blood Seeker', `PetSpellDataId` = 0 WHERE `entry` = 3868;
UPDATE `creature_template` SET `name` = 'Razormane Wolf', `PetSpellDataId` = 0 WHERE `entry` = 3939;
UPDATE `creature_template` SET `name` = 'Needles Cougar', `PetSpellDataId` = 0 WHERE `entry` = 4124;
UPDATE `creature_template` SET `name` = 'Hecklefang Hyena', `PetSpellDataId` = 0 WHERE `entry` = 4127;
UPDATE `creature_template` SET `name` = 'Hecklefang Stalker', `PetSpellDataId` = 0 WHERE `entry` = 4128;
UPDATE `creature_template` SET `name` = 'Hecklefang Snarler', `PetSpellDataId` = 0 WHERE `entry` = 4129;
UPDATE `creature_template` SET `name` = 'Sparkleshell Tortoise', `PetSpellDataId` = 0 WHERE `entry` = 4142;
UPDATE `creature_template` SET `name` = 'Sparkleshell Borer', `PetSpellDataId` = 0 WHERE `entry` = 4144;
UPDATE `creature_template` SET `name` = 'Salt Flats Scavenger', `PetSpellDataId` = 0 WHERE `entry` = 4154;
UPDATE `creature_template` SET `name` = 'Pesterhide Hyena', `PetSpellDataId` = 0 WHERE `entry` = 4248;
UPDATE `creature_template` SET `name` = 'Pesterhide Snarler', `PetSpellDataId` = 0 WHERE `entry` = 4249;
UPDATE `creature_template` SET `name` = 'Galak Packhound', `PetSpellDataId` = 0 WHERE `entry` = 4250;
UPDATE `creature_template` SET `name` = 'Deepmoss Matriarch', `PetSpellDataId` = 0 WHERE `entry` = 4264;
UPDATE `creature_template` SET `name` = 'Kolkar Packhound', `PetSpellDataId` = 0 WHERE `entry` = 4316;
UPDATE `creature_template` SET `name` = 'Drywallow Vicejaw', `PetSpellDataId` = 0 WHERE `entry` = 4342;
UPDATE `creature_template` SET `name` = 'Bloodfen Raptor', `PetSpellDataId` = 0 WHERE `entry` = 4351;
UPDATE `creature_template` SET `name` = 'Bloodfen Screecher', `PetSpellDataId` = 0 WHERE `entry` = 4352;
UPDATE `creature_template` SET `name` = 'Bloodfen Scytheclaw', `PetSpellDataId` = 0 WHERE `entry` = 4355;
UPDATE `creature_template` SET `name` = 'Bloodfen Razormaw', `PetSpellDataId` = 0 WHERE `entry` = 4356;
UPDATE `creature_template` SET `name` = 'Bloodfen Lashtail', `PetSpellDataId` = 0 WHERE `entry` = 4357;
UPDATE `creature_template` SET `name` = 'Mudrock Spikeshell', `PetSpellDataId` = 0 WHERE `entry` = 4397;
UPDATE `creature_template` SET `name` = 'Mudrock Burrower', `PetSpellDataId` = 0 WHERE `entry` = 4398;
UPDATE `creature_template` SET `name` = 'Mudrock Borer', `PetSpellDataId` = 0 WHERE `entry` = 4399;
UPDATE `creature_template` SET `name` = 'Darkfang Venomspitter', `PetSpellDataId` = 0 WHERE `entry` = 4414;
UPDATE `creature_template` SET `name` = 'Giant Darkfang Spider', `PetSpellDataId` = 0 WHERE `entry` = 4415;
UPDATE `creature_template` SET `name` = 'Tamed Hyena', `PetSpellDataId` = 0 WHERE `entry` = 4534;
UPDATE `creature_template` SET `name` = 'Tamed Battleboar', `PetSpellDataId` = 0 WHERE `entry` = 4535;
UPDATE `creature_template` SET `name` = 'Steelsnap', `PetSpellDataId` = 0 WHERE `entry` = 4548;
UPDATE `creature_template` SET `name` = 'Maraudine Bonepaw', `PetSpellDataId` = 0 WHERE `entry` = 4660;
UPDATE `creature_template` SET `name` = 'Starving Bonepaw', `PetSpellDataId` = 0 WHERE `entry` = 4689;
UPDATE `creature_template` SET `name` = 'Rabid Bonepaw', `PetSpellDataId` = 0 WHERE `entry` = 4690;
UPDATE `creature_template` SET `name` = 'Dread Swoop', `PetSpellDataId` = 0 WHERE `entry` = 4692;
UPDATE `creature_template` SET `name` = 'Carrion Horror', `PetSpellDataId` = 0 WHERE `entry` = 4695;
UPDATE `creature_template` SET `name` = 'Murk Slitherer', `PetSpellDataId` = 10544 WHERE `entry` = 5224;
UPDATE `creature_template` SET `name` = 'Murk Spitter', `PetSpellDataId` = 10544 WHERE `entry` = 5225;
UPDATE `creature_template` SET `name` = 'Groddoc Ape', `PetSpellDataId` = 0 WHERE `entry` = 5260;
UPDATE `creature_template` SET `name` = 'Grizzled Ironfur Bear', `PetSpellDataId` = 0 WHERE `entry` = 5272;
UPDATE `creature_template` SET `name` = 'Rabid Longtooth', `PetSpellDataId` = 0 WHERE `entry` = 5288;
UPDATE `creature_template` SET `name` = 'Surf Glider', `PetSpellDataId` = 0 WHERE `entry` = 5431;
UPDATE `creature_template` SET `name` = 'Deviate Viper', `PetSpellDataId` = 10543 WHERE `entry` = 5755;
UPDATE `creature_template` SET `name` = 'The Rake', `PetSpellDataId` = 0 WHERE `entry` = 5807;
UPDATE `creature_template` SET `name` = 'Humar the Pridelord', `PetSpellDataId` = 0 WHERE `entry` = 5828;
UPDATE `creature_template` SET `name` = 'Snort the Heckler', `PetSpellDataId` = 0 WHERE `entry` = 5829;
UPDATE `creature_template` SET `name` = 'Azzere the Skyblade', `PetSpellDataId` = 0 WHERE `entry` = 5834;
UPDATE `creature_template` SET `name` = 'Takk the Leaper', `PetSpellDataId` = 0 WHERE `entry` = 5842;
UPDATE `creature_template` SET `name` = 'Searing Lava Spider', `PetSpellDataId` = 0 WHERE `entry` = 5857;
UPDATE `creature_template` SET `name` = 'Greater Lava Spider', `PetSpellDataId` = 0 WHERE `entry` = 5858;
UPDATE `creature_template` SET `name` = 'Dishu', `PetSpellDataId` = 0 WHERE `entry` = 5865;
UPDATE `creature_template` SET `name` = 'Black Slayer', `PetSpellDataId` = 0 WHERE `entry` = 5982;
UPDATE `creature_template` SET `name` = 'Bonepicker', `PetSpellDataId` = 0 WHERE `entry` = 5983;
UPDATE `creature_template` SET `name` = 'Starving Snickerfang', `PetSpellDataId` = 0 WHERE `entry` = 5984;
UPDATE `creature_template` SET `name` = 'Snickerfang Hyena', `PetSpellDataId` = 0 WHERE `entry` = 5985;
UPDATE `creature_template` SET `name` = 'Coralshell Lurker', `PetSpellDataId` = 0 WHERE `entry` = 6352;
UPDATE `creature_template` SET `name` = 'Coralshell Tortoise', `PetSpellDataId` = 0 WHERE `entry` = 6369;
UPDATE `creature_template` SET `name` = 'Ravasaur', `PetSpellDataId` = 0 WHERE `entry` = 6505;
UPDATE `creature_template` SET `name` = 'Ravasaur Runner', `PetSpellDataId` = 0 WHERE `entry` = 6506;
UPDATE `creature_template` SET `name` = 'Ravasaur Hunter', `PetSpellDataId` = 0 WHERE `entry` = 6507;
UPDATE `creature_template` SET `name` = 'Venomhide Ravasaur', `PetSpellDataId` = 0 WHERE `entry` = 6508;
UPDATE `creature_template` SET `name` = 'Un\'Goro Stomper', `PetSpellDataId` = 0 WHERE `entry` = 6513;
UPDATE `creature_template` SET `name` = 'Un\'Goro Gorilla', `PetSpellDataId` = 0 WHERE `entry` = 6514;
UPDATE `creature_template` SET `name` = 'Ravasaur Matriarch', `PetSpellDataId` = 0 WHERE `entry` = 6581;
UPDATE `creature_template` SET `name` = 'Thistle Cub', `PetSpellDataId` = 0 WHERE `entry` = 6789;
UPDATE `creature_template` SET `name` = 'Tracking Hound', `PetSpellDataId` = 0 WHERE `entry` = 6867;
UPDATE `creature_template` SET `name` = 'Sandfury Guardian', `PetSpellDataId` = 10544 WHERE `entry` = 7268;
UPDATE `creature_template` SET `name` = 'Sky Shadow', `PetSpellDataId` = 0 WHERE `entry` = 7376;
UPDATE `creature_template` SET `name` = 'Frostsaber', `PetSpellDataId` = 0 WHERE `entry` = 7431;
UPDATE `creature_template` SET `name` = 'Frostsaber Pride Watcher', `PetSpellDataId` = 0 WHERE `entry` = 7434;
UPDATE `creature_template` SET `name` = 'Shardtooth Mauler', `PetSpellDataId` = 0 WHERE `entry` = 7443;
UPDATE `creature_template` SET `name` = 'Rabid Shardtooth', `PetSpellDataId` = 0 WHERE `entry` = 7446;
UPDATE `creature_template` SET `name` = 'Gammerita', `PetSpellDataId` = 0 WHERE `entry` = 7977;
UPDATE `creature_template` SET `name` = 'Angerclaw Bear', `PetSpellDataId` = 0 WHERE `entry` = 8956;
UPDATE `creature_template` SET `name` = 'Angerclaw Grizzly', `PetSpellDataId` = 0 WHERE `entry` = 8957;
UPDATE `creature_template` SET `name` = 'Felpaw Scavenger', `PetSpellDataId` = 0 WHERE `entry` = 8960;
UPDATE `creature_template` SET `name` = 'Lar\'korwi Mate', `PetSpellDataId` = 0 WHERE `entry` = 9683;
UPDATE `creature_template` SET `name` = 'Lar\'korwi', `PetSpellDataId` = 0 WHERE `entry` = 9684;
UPDATE `creature_template` SET `name` = 'Ember Worg', `PetSpellDataId` = 0 WHERE `entry` = 9690;
UPDATE `creature_template` SET `name` = 'Slavering Ember Worg', `PetSpellDataId` = 0 WHERE `entry` = 9694;
UPDATE `creature_template` SET `name` = 'Giant Ember Worg', `PetSpellDataId` = 0 WHERE `entry` = 9697;
UPDATE `creature_template` SET `name` = 'Deathmaw', `PetSpellDataId` = 0 WHERE `entry` = 10077;
UPDATE `creature_template` SET `name` = 'Bloodaxe Worg Pup', `PetSpellDataId` = 0 WHERE `entry` = 10221;
UPDATE `creature_template` SET `name` = 'Ressan the Needler', `PetSpellDataId` = 0 WHERE `entry` = 10357;
UPDATE `creature_template` SET `name` = 'Shy-Rotam', `PetSpellDataId` = 0 WHERE `entry` = 10737;
UPDATE `creature_template` SET `name` = 'Sian-Rotam', `PetSpellDataId` = 0 WHERE `entry` = 10741;
UPDATE `creature_template` SET `name` = 'Ursius', `PetSpellDataId` = 0 WHERE `entry` = 10806;
UPDATE `creature_template` SET `name` = 'Arikara', `PetSpellDataId` = 0 WHERE `entry` = 10882;
UPDATE `creature_template` SET `name` = 'Scarlet Hound', `PetSpellDataId` = 0 WHERE `entry` = 10979;
UPDATE `creature_template` SET `name` = 'Frostwolf', `PetSpellDataId` = 0 WHERE `entry` = 10981;
UPDATE `creature_template` SET `name` = 'Zulian Cub', `PetSpellDataId` = 0 WHERE `entry` = 11360;
UPDATE `creature_template` SET `name` = 'Zulian Tiger', `PetSpellDataId` = 0 WHERE `entry` = 11361;
UPDATE `creature_template` SET `name` = 'Bloodseeker Bat', `PetSpellDataId` = 0 WHERE `entry` = 11368;
UPDATE `creature_template` SET `name` = 'Razzashi Serpent', `PetSpellDataId` = 10530 WHERE `entry` = 11371;
UPDATE `creature_template` SET `name` = 'Razzashi Adder', `PetSpellDataId` = 10530 WHERE `entry` = 11372;
UPDATE `creature_template` SET `name` = 'Razzashi Cobra', `PetSpellDataId` = 10530 WHERE `entry` = 11373;
UPDATE `creature_template` SET `name` = 'Sand Skitterer', `PetSpellDataId` = 0 WHERE `entry` = 11738;
UPDATE `creature_template` SET `name` = 'Besseleth', `PetSpellDataId` = 5892 WHERE `entry` = 11921;
UPDATE `creature_template` SET `name` = 'Ursol\'lok', `PetSpellDataId` = 0 WHERE `entry` = 12037;
UPDATE `creature_template` SET `name` = 'Enraged Reef Crawler', `PetSpellDataId` = 0 WHERE `entry` = 12347;
UPDATE `creature_template` SET `name` = 'Gordok Hyena', `PetSpellDataId` = 0 WHERE `entry` = 12418;
UPDATE `creature_template` SET `name` = 'Gorefang', `PetSpellDataId` = 0 WHERE `entry` = 12431;
UPDATE `creature_template` SET `name` = 'Old Vicejaw', `PetSpellDataId` = 0 WHERE `entry` = 12432;
UPDATE `creature_template` SET `name` = 'Gordok Mastiff', `PetSpellDataId` = 0 WHERE `entry` = 13036;
UPDATE `creature_template` SET `name` = 'Steeljaw Snapper', `PetSpellDataId` = 0 WHERE `entry` = 14123;
UPDATE `creature_template` SET `name` = 'Araga', `PetSpellDataId` = 0 WHERE `entry` = 14222;
UPDATE `creature_template` SET `name` = 'Cranky Benj', `PetSpellDataId` = 5924 WHERE `entry` = 14223;
UPDATE `creature_template` SET `name` = 'Giggler', `PetSpellDataId` = 0 WHERE `entry` = 14228;
UPDATE `creature_template` SET `name` = 'Dart', `PetSpellDataId` = 0 WHERE `entry` = 14232;
UPDATE `creature_template` SET `name` = 'Ripscale', `PetSpellDataId` = 5858 WHERE `entry` = 14233;
UPDATE `creature_template` SET `name` = 'Hayoc', `PetSpellDataId` = 0 WHERE `entry` = 14234;
UPDATE `creature_template` SET `name` = 'Lord Condar', `PetSpellDataId` = 0 WHERE `entry` = 14268;
UPDATE `creature_template` SET `name` = 'Big Samras', `PetSpellDataId` = 0 WHERE `entry` = 14280;
UPDATE `creature_template` SET `name` = 'Stormpike Owl', `PetSpellDataId` = 0 WHERE `entry` = 14283;
UPDATE `creature_template` SET `name` = 'Mongress', `PetSpellDataId` = 5808 WHERE `entry` = 14344;
UPDATE `creature_template` SET `name` = 'Duskstalker', `PetSpellDataId` = 0 WHERE `entry` = 14430;
UPDATE `creature_template` SET `name` = 'Gretheer', `PetSpellDataId` = 0 WHERE `entry` = 14472;
UPDATE `creature_template` SET `name` = 'Krellack', `PetSpellDataId` = 8861 WHERE `entry` = 14476;
UPDATE `creature_template` SET `name` = 'Kurmokk', `PetSpellDataId` = 0 WHERE `entry` = 14491;
UPDATE `creature_template` SET `name` = 'Razzashi Raptor', `PetSpellDataId` = 0 WHERE `entry` = 14821;
UPDATE `creature_template` SET `name` = 'Frenzied Bloodseeker Bat', `PetSpellDataId` = 0 WHERE `entry` = 14965;
UPDATE `creature_template` SET `name` = 'Zulian Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 15043;
UPDATE `creature_template` SET `name` = 'Zulian Guardian', `PetSpellDataId` = 8271 WHERE `entry` = 15068;
UPDATE `creature_template` SET `name` = 'Springpaw Cub', `PetSpellDataId` = 0 WHERE `entry` = 15366;
UPDATE `creature_template` SET `name` = 'Springpaw Lynx', `PetSpellDataId` = 0 WHERE `entry` = 15372;
UPDATE `creature_template` SET `name` = 'Dread Creeper', `PetSpellDataId` = 0 WHERE `entry` = 15974;
UPDATE `creature_template` SET `name` = 'Carrion Spinner', `PetSpellDataId` = 0 WHERE `entry` = 15975;
UPDATE `creature_template` SET `name` = 'Venom Stalker', `PetSpellDataId` = 0 WHERE `entry` = 15976;
UPDATE `creature_template` SET `name` = 'Shadowbat', `PetSpellDataId` = 0 WHERE `entry` = 16173;
UPDATE `creature_template` SET `name` = 'Greater Shadowbat', `PetSpellDataId` = 0 WHERE `entry` = 16174;
UPDATE `creature_template` SET `name` = 'Vampiric Shadowbat', `PetSpellDataId` = 0 WHERE `entry` = 16175;
UPDATE `creature_template` SET `name` = 'Mistbat', `PetSpellDataId` = 0 WHERE `entry` = 16353;
UPDATE `creature_template` SET `name` = 'Vampiric Mistbat', `PetSpellDataId` = 0 WHERE `entry` = 16354;
UPDATE `creature_template` SET `name` = 'Lesser Scourgebat', `PetSpellDataId` = 0 WHERE `entry` = 16355;
UPDATE `creature_template` SET `name` = 'Necro Stalker', `PetSpellDataId` = 0 WHERE `entry` = 16453;
UPDATE `creature_template` SET `name` = 'Vale Moth', `PetSpellDataId` = 0 WHERE `entry` = 16520;
UPDATE `creature_template` SET `name` = 'Razorfang Ravager', `PetSpellDataId` = 0 WHERE `entry` = 16933;
UPDATE `creature_template` SET `name` = 'Bonestripper Buzzard', `PetSpellDataId` = 0 WHERE `entry` = 16972;
UPDATE `creature_template` SET `name` = 'Bonestripper Vulture', `PetSpellDataId` = 0 WHERE `entry` = 16973;
UPDATE `creature_template` SET `name` = 'Goretooth', `PetSpellDataId` = 0 WHERE `entry` = 17144;
UPDATE `creature_template` SET `name` = 'Infected Nightstalker Runt', `PetSpellDataId` = 0 WHERE `entry` = 17202;
UPDATE `creature_template` SET `name` = 'Nightstalker', `PetSpellDataId` = 0 WHERE `entry` = 17203;
UPDATE `creature_template` SET `name` = 'Skittering Crawler', `PetSpellDataId` = 0 WHERE `entry` = 17216;
UPDATE `creature_template` SET `name` = 'Barbed Crawler', `PetSpellDataId` = 0 WHERE `entry` = 17217;
UPDATE `creature_template` SET `name` = 'Vampiric Tracker', `PetSpellDataId` = 0 WHERE `entry` = 17221;
UPDATE `creature_template` SET `name` = 'Tcha\'kaz', `PetSpellDataId` = 5904 WHERE `entry` = 17236;
UPDATE `creature_template` SET `name` = 'Brown Bear', `PetSpellDataId` = 0 WHERE `entry` = 17345;
UPDATE `creature_template` SET `name` = 'Grizzled Brown Bear', `PetSpellDataId` = 0 WHERE `entry` = 17347;
UPDATE `creature_template` SET `name` = 'Elder Brown Bear', `PetSpellDataId` = 0 WHERE `entry` = 17348;
UPDATE `creature_template` SET `name` = 'Timberstrider Fledgling', `PetSpellDataId` = 0 WHERE `entry` = 17372;
UPDATE `creature_template` SET `name` = 'Timberstrider', `PetSpellDataId` = 0 WHERE `entry` = 17373;
UPDATE `creature_template` SET `name` = 'Greater Timberstrider', `PetSpellDataId` = 0 WHERE `entry` = 17374;
UPDATE `creature_template` SET `name` = 'Myst Spinner', `PetSpellDataId` = 0 WHERE `entry` = 17522;
UPDATE `creature_template` SET `name` = 'Myst Leecher', `PetSpellDataId` = 0 WHERE `entry` = 17523;
UPDATE `creature_template` SET `name` = 'Bloodmyst Hatchling', `PetSpellDataId` = 0 WHERE `entry` = 17525;
UPDATE `creature_template` SET `name` = 'Deathclaw', `PetSpellDataId` = 0 WHERE `entry` = 17661;
UPDATE `creature_template` SET `name` = 'Zarakh', `PetSpellDataId` = 0 WHERE `entry` = 17683;
UPDATE `creature_template` SET `name` = 'Underbat', `PetSpellDataId` = 0 WHERE `entry` = 17724;
UPDATE `creature_template` SET `name` = 'Fen Ray', `PetSpellDataId` = 0 WHERE `entry` = 17731;
UPDATE `creature_template` SET `name` = 'Underbat Swarmer', `PetSpellDataId` = 0 WHERE `entry` = 17736;
UPDATE `creature_template` SET `name` = 'Darkwater Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 17952;
UPDATE `creature_template` SET `name` = 'Marshfang Ripper', `PetSpellDataId` = 0 WHERE `entry` = 18130;
UPDATE `creature_template` SET `name` = 'Marshfang Slicer', `PetSpellDataId` = 0 WHERE `entry` = 18131;
UPDATE `creature_template` SET `name` = 'Crusty', `PetSpellDataId` = 0 WHERE `entry` = 18241;
UPDATE `creature_template` SET `name` = 'Sporewing', `PetSpellDataId` = 0 WHERE `entry` = 18280;
UPDATE `creature_template` SET `name` = '\"Count\" Ungula', `PetSpellDataId` = 0 WHERE `entry` = 18285;
UPDATE `creature_template` SET `name` = 'Vicious Teromoth', `PetSpellDataId` = 0 WHERE `entry` = 18437;
UPDATE `creature_template` SET `name` = 'Teromoth', `PetSpellDataId` = 0 WHERE `entry` = 18468;
UPDATE `creature_template` SET `name` = 'Royal Teromoth', `PetSpellDataId` = 0 WHERE `entry` = 18469;
UPDATE `creature_template` SET `name` = 'Bonelasher', `PetSpellDataId` = 0 WHERE `entry` = 18470;
UPDATE `creature_template` SET `name` = 'Timber Worg Alpha', `PetSpellDataId` = 0 WHERE `entry` = 18477;
UPDATE `creature_template` SET `name` = 'Deathskitter', `PetSpellDataId` = 0 WHERE `entry` = 18647;
UPDATE `creature_template` SET `name` = 'Ironjaw', `PetSpellDataId` = 0 WHERE `entry` = 18670;
UPDATE `creature_template` SET `name` = 'Nether Ray', `PetSpellDataId` = 0 WHERE `entry` = 18880;
UPDATE `creature_template` SET `name` = 'Sable Jaguar', `PetSpellDataId` = 0 WHERE `entry` = 18982;
UPDATE `creature_template` SET `name` = 'Blackfang Tarantula', `PetSpellDataId` = 0 WHERE `entry` = 18983;
UPDATE `creature_template` SET `name` = 'Bleeding Hollow Worg', `PetSpellDataId` = 0 WHERE `entry` = 19423;
UPDATE `creature_template` SET `name` = 'Avian Darkhawk', `PetSpellDataId` = 0 WHERE `entry` = 19429;
UPDATE `creature_template` SET `name` = 'Ripp', `PetSpellDataId` = 0 WHERE `entry` = 19458;
UPDATE `creature_template` SET `name` = 'Feng', `PetSpellDataId` = 0 WHERE `entry` = 19459;
UPDATE `creature_template` SET `name` = 'Darkwater Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 20075;
UPDATE `creature_template` SET `name` = 'Fen Ray (1)', `PetSpellDataId` = 0 WHERE `entry` = 20173;
UPDATE `creature_template` SET `name` = 'Underbat (1)', `PetSpellDataId` = 0 WHERE `entry` = 20185;
UPDATE `creature_template` SET `name` = 'Underbat Swarmer (1)', `PetSpellDataId` = 0 WHERE `entry` = 20186;
UPDATE `creature_template` SET `name` = 'Bloodthirsty Marshfang', `PetSpellDataId` = 0 WHERE `entry` = 20196;
UPDATE `creature_template` SET `name` = 'Shimmerwing Moth', `PetSpellDataId` = 0 WHERE `entry` = 20611;
UPDATE `creature_template` SET `name` = 'Terokkarantula', `PetSpellDataId` = 0 WHERE `entry` = 20682;
UPDATE `creature_template` SET `name` = 'Avian Darkhawk (1)', `PetSpellDataId` = 0 WHERE `entry` = 20686;
UPDATE `creature_template` SET `name` = 'Ridgespine Stalker', `PetSpellDataId` = 0 WHERE `entry` = 20714;
UPDATE `creature_template` SET `name` = 'Bladespire Raptor', `PetSpellDataId` = 0 WHERE `entry` = 20728;
UPDATE `creature_template` SET `name` = 'Bladespire Ravager', `PetSpellDataId` = 0 WHERE `entry` = 20729;
UPDATE `creature_template` SET `name` = 'Thunderlord Dire Wolf', `PetSpellDataId` = 0 WHERE `entry` = 20748;
UPDATE `creature_template` SET `name` = 'Daggermaw Lashtail', `PetSpellDataId` = 0 WHERE `entry` = 20751;
UPDATE `creature_template` SET `name` = 'Grand Silkwing', `PetSpellDataId` = 0 WHERE `entry` = 20752;
UPDATE `creature_template` SET `name` = 'Barbscale Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 20773;
UPDATE `creature_template` SET `name` = 'Ridgespine Horror', `PetSpellDataId` = 0 WHERE `entry` = 20998;
UPDATE `creature_template` SET `name` = 'Felsworn Daggermaw', `PetSpellDataId` = 0 WHERE `entry` = 21124;
UPDATE `creature_template` SET `name` = 'Coilfang Ray', `PetSpellDataId` = 0 WHERE `entry` = 21128;
UPDATE `creature_template` SET `name` = 'Rubicund Silkwing', `PetSpellDataId` = 0 WHERE `entry` = 21372;
UPDATE `creature_template` SET `name` = 'Silkwing', `PetSpellDataId` = 0 WHERE `entry` = 21373;
UPDATE `creature_template` SET `name` = 'Trachela', `PetSpellDataId` = 0 WHERE `entry` = 21515;
UPDATE `creature_template` SET `name` = 'Forest Strider', `PetSpellDataId` = 5918 WHERE `entry` = 21634;
UPDATE `creature_template` SET `name` = 'Blackwind Sabercat', `PetSpellDataId` = 0 WHERE `entry` = 21723;
UPDATE `creature_template` SET `name` = 'Hawkbane', `PetSpellDataId` = 0 WHERE `entry` = 21724;
UPDATE `creature_template` SET `name` = 'Skettis Kaliri', `PetSpellDataId` = 10709 WHERE `entry` = 21804;
UPDATE `creature_template` SET `name` = 'Mature Silkwing', `PetSpellDataId` = 0 WHERE `entry` = 21839;
UPDATE `creature_template` SET `name` = 'Coilfang Ray (1)', `PetSpellDataId` = 0 WHERE `entry` = 21841;
UPDATE `creature_template` SET `name` = 'Avian Ripper', `PetSpellDataId` = 0 WHERE `entry` = 21891;
UPDATE `creature_template` SET `name` = 'Netherskate', `PetSpellDataId` = 0 WHERE `entry` = 21901;
UPDATE `creature_template` SET `name` = 'Avian Warhawk', `PetSpellDataId` = 0 WHERE `entry` = 21904;
UPDATE `creature_template` SET `name` = 'Avian Ripper (1)', `PetSpellDataId` = 0 WHERE `entry` = 21989;
UPDATE `creature_template` SET `name` = 'Avian Warhawk (1)', `PetSpellDataId` = 0 WHERE `entry` = 21990;
UPDATE `creature_template` SET `name` = 'Cavern Crawler', `PetSpellDataId` = 0 WHERE `entry` = 22044;
UPDATE `creature_template` SET `name` = 'Daggermaw Blackhide', `PetSpellDataId` = 0 WHERE `entry` = 22052;
UPDATE `creature_template` SET `name` = 'Mature Cavern Crawler', `PetSpellDataId` = 0 WHERE `entry` = 22132;
UPDATE `creature_template` SET `name` = 'Blackfang Tarantula (1)', `PetSpellDataId` = 0 WHERE `entry` = 22162;
UPDATE `creature_template` SET `name` = 'Darkwater Crocolisk (1)', `PetSpellDataId` = 0 WHERE `entry` = 22163;
UPDATE `creature_template` SET `name` = 'Sable Jaguar (1)', `PetSpellDataId` = 0 WHERE `entry` = 22173;
UPDATE `creature_template` SET `name` = 'Shadowwing Owl', `PetSpellDataId` = 10712 WHERE `entry` = 22265;
UPDATE `creature_template` SET `name` = 'Frostwolf (1)', `PetSpellDataId` = 0 WHERE `entry` = 22737;
UPDATE `creature_template` SET `name` = 'Stormpike Owl (1)', `PetSpellDataId` = 0 WHERE `entry` = 22767;
UPDATE `creature_template` SET `name` = 'Gezzarak the Huntress', `PetSpellDataId` = 0 WHERE `entry` = 23163;
UPDATE `creature_template` SET `name` = 'Blackwind Warp Chaser', `PetSpellDataId` = 11576 WHERE `entry` = 23219;
UPDATE `creature_template` SET `name` = 'Nethermine Ravager', `PetSpellDataId` = 0 WHERE `entry` = 23326;
UPDATE `creature_template` SET `name` = 'Netherwing Ray', `PetSpellDataId` = 0 WHERE `entry` = 23501;
UPDATE `creature_template` SET `name` = 'Goreclaw the Ravenous', `PetSpellDataId` = 0 WHERE `entry` = 23873;
UPDATE `creature_template` SET `name` = 'Amani Lynx', `PetSpellDataId` = 0 WHERE `entry` = 24043;
UPDATE `creature_template` SET `name` = 'Amani Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 24047;
UPDATE `creature_template` SET `name` = 'Amani Lynx Cub', `PetSpellDataId` = 0 WHERE `entry` = 24064;
UPDATE `creature_template` SET `name` = 'Tamed Amani Crocolisk', `PetSpellDataId` = 0 WHERE `entry` = 24138;
UPDATE `creature_template` SET `name` = 'Amani Elder Lynx', `PetSpellDataId` = 0 WHERE `entry` = 24530;
UPDATE `creature_template` SET `name` = 'Razorthorn Ravager', `PetSpellDataId` = 0 WHERE `entry` = 24922;
